### ISSUE TITLE
Add support for ⌘-⇧-C to copy the current URL

### ISSUE THREAD

**Issue by chrismessina** [jcsalterego/Sky.app#1]
I use this shortcut in Arc all the time. Would love Sky to support this!

**Comment by jcsalterego** [comment]
Added in 6d924d01c3db4d362fc93e9f1607fd361758ddb8 and available in 0.0.5: https://github.com/jcsalterego/Sky.app/releases/tag/0.0.5

I was dropping my kid off at dance class and overheard someone tell her friend: "I think you're supposed to press the hashtag button before entering the door code." Imagine that!

**Comment by chrismessina** [comment]
@jcsalterego dang you're fast! 

And also, tell your kid's friend that I said they're #awesome.
