### ISSUE TITLE
Do you want this to be notarized?

### ISSUE THREAD

**Issue by filmgirl** [jcsalterego/Sky.app#2]
I can help with the build/notarization process if you want that, just LMK. Happy to use my dev account for something!

**Comment by jcsalterego** [comment]
Thanks for the kind offer! The DMG found in Releases _should_ be notarized and signed with my developer account.

Or is it giving you grief when you try to run it?

**Comment by filmgirl** [comment]
Yeah, I get a "this might harm your machine" message every time I open the DMG/do the first run. Haven't tried 0.08 yet.

**Comment by jcsalterego** [comment]
Ahhh okay looks like I may need to take some remedial app packaging classes. I'll investigate and may ask for your help in testing!

**Comment by jcsalterego** [comment]
OK, looks like I have to setup Hardened Runtime and upload to Apple for notarization... I'll get this going soon.

**Comment by jcsalterego** [comment]
@filmgirl Do you mind testing the 0.1.0 DMG? https://github.com/jcsalterego/Sky.app/releases/tag/0.1.0

**Comment by jcsalterego** [comment]
App is notarized but still confirming whether the DMG looks notarized to folks.

**Comment by jcsalterego** [comment]
OK, I think the latest 0.1.2 release is properly notarized - https://github.com/jcsalterego/Sky.app/releases/tag/0.1.2

Thanks for pointing this out @filmgirl!
