### ISSUE TITLE
White title bar and scroll bar

### ISSUE THREAD

**Issue by gingerbeardman** [jcsalterego/Sky.app#24]
Not sure why I'm seeing different to your screenshot.

The app always looks like this for me, regardless of system dark/light mode setting.

I have BlueSky preference set to "System"

<img width="712" alt="Screen shot 2024-10-20 at 23 28 53" src="https://github.com/user-attachments/assets/0dd36b6d-41cf-44f5-8ada-0ea9f73ee5bd">

**Comment by jcsalterego** [comment]
This should be fixed once I roll out https://github.com/jcsalterego/Sky.app/pull/27

**Comment by jcsalterego** [comment]
Closed by https://github.com/jcsalterego/Sky.app/pull/27

**Comment by gingerbeardman** [comment]
Cheers and season's greetings
