### ISSUE TITLE
Feature request: Auto refresh

### ISSUE THREAD

**Issue by mwhdc** [jcsalterego/Sky.app#25]
Great app, love that it isn't an Electron monstrosity. I have been running it as a persistent social sidebar across all my desktop spaces.

One feature I miss from the birdhellsite app is streaming of new posts, with the timeline either fixed at last read post or pinned (autoscrolling) to the most recent post loaded.

If others are interested in the feature, I would suggest offering an option to refresh every x seconds (with a respectful minimum) and autoscrolling to the top whenever a refresh occurs.

**Comment by victorcerutti** [comment]
I completely agree 👍 
Auto-refresh would be cool 
But keeping the scrolling position on the last read post after a refresh (manual or auto) is really something I miss right now

**Comment by jcsalterego** [comment]
This would be cool but would require the automation of clicking the "more posts" button.

I think this is better served as a feature request for the app itself https://github.com/bluesky-social/social-app/issues/new

**Comment by mwhdc** [comment]
That makes sense. Existing request [here](https://github.com/bluesky-social/social-app/issues/6954).
