### ISSUE TITLE
Feature request: Columns

### ISSUE THREAD

**Issue by twist-shipper** [jcsalterego/Sky.app#26]
It would be amazing to have a desktop-native multi-columnar view similar to a TweetBot (former Twitter client) or Ivory (current Mastodon) client. Capsulized web-site "apps" just don't do it well. :-\

Thanks for listening! :)

**Comment by jcsalterego** [comment]
Yeah, this would be cool but Sky.app is really meant to a fairly thin layer on the official app. You may consider looking at the existing issues or submitting a new one in the official app https://github.com/bluesky-social/social-app/issues
