### ISSUE TITLE
Stuck notifications

### ISSUE THREAD

**Issue by muttmutt** [jcsalterego/Sky.app#28]
I don't know if this is an app issue or an OS issue. I can't clear the notification from the icon, it's stuck at 3.
<img width="35" alt="image" src="https://github.com/user-attachments/assets/4b157369-cd12-46a5-9098-d61c01291e57" />

I've tried uninstalling and re-installing. I've tried signing out and back in. Nothing clears it.

Any ideas?

**Comment by muttmutt** [comment]
Never mind!

`killall Dock`

fixed it. My bad.

**Comment by muttmutt** [comment]
Closing

**Comment by jcsalterego** [comment]
whew!

**Comment by jcsalterego** [comment]
also: you may try cmd-shift-R which does a full reload. that should clear up the badge too

**Comment by muttmutt** [comment]
It's back. It won't stay cleared.
