### ISSUE TITLE
Unable to attach images in the post composer

### ISSUE THREAD

**Issue by a2** [jcsalterego/Sky.app#3]
I'm not sure if there are errors in the console when I tap on the <img src="https://user-images.githubusercontent.com/241156/236649494-2c15cd09-2882-4b81-a33a-c59f8683ad08.png" alt="Image Upload" width="21" /> button?

**Comment by jcsalterego** [comment]
Yes! This is an outstanding bug / missing feature and is on the list.

**Comment by jcsalterego** [comment]
This is fixed in https://github.com/jcsalterego/Sky.app/releases/0.1.1
