### ISSUE TITLE
Icon message counter still stuck

### ISSUE THREAD

**Issue by muttmutt** [jcsalterego/Sky.app#31]
The Sky app's unread message counter refused to be reset.
<img width="77" alt="Screenshot 2024-12-26 at 4 22 27 PM" src="https://github.com/user-attachments/assets/5f9e1894-9abb-4475-a443-1b4e8803b264" />

**Comment by jcsalterego** [comment]
this should be the sum of unread messages and you'll need to scroll up all the way with the Notifications > All tab.

Try:

- going to the notifications tab
- the All tab
- and click on the bell icon until the bell badge clears

<img width="62" alt="image" src="https://github.com/user-attachments/assets/c1a9539a-7a75-458c-8183-edfd85cbd9b1" />
<img width="65" alt="image" src="https://github.com/user-attachments/assets/17d6eebc-cffb-47c9-b291-827419684fda" />

- then a refresh (cmd-shift-R)

**Comment by muttmutt** [comment]
Sorry, this didn't work. The Bell is clear and cmd-shift-R didn't help. The icon still says "3". 
<img width="76" alt="image" src="https://github.com/user-attachments/assets/288e7e7b-eec5-4f77-b867-68179cdd0f6d" />

**Comment by jcsalterego** [comment]
@muttmutt hmmm I wonder if this is related to muting. I'll have to dig into it

**Comment by muttmutt** [comment]
Once again, I am an idiot. It was DMs. The app didn't show any unread DMs in the UI, but when I went into it, there were 3. ¯\_(ツ)_/¯

Sorry.

**Comment by jcsalterego** [comment]
@muttmutt No problem! I'm glad you found the cause of the mysterious badge.
