### ISSUE TITLE
Images should pop out into their own window

### ISSUE THREAD

**Issue by amancevice** [jcsalterego/Sky.app#4]
Thanks for publishing this app—When embiggening an image it currently loads in the main Sky app window, making the image quite small. The Twitter macOS app pops media out into their own window in a more reasonable size.

**Comment by jcsalterego** [comment]
Thanks for the suggestion! It would require a bit of elbow grease hooking into the image carousel code, and displaying the images in their own windows. I'll think on it!

**Comment by jcsalterego** [comment]
Unfortunately I am going to close this issue.
