### ISSUE TITLE
Consider adding Sparkle support?

### ISSUE THREAD

**Issue by filmgirl** [jcsalterego/Sky.app#5]
It would be great if there was an easy way to update the app when a new version is pushed to GitHub. See [https://sparkle-project.org/documentation/](https://sparkle-project.org/documentation/) for more info. Conversely, I suppose I could just do the work and find a way to get this in my own Homebrew tap (or submit it to homebrew properly) and do updates that way via git.

Thank you for your continued work!

**Comment by jcsalterego** [comment]
Absolutely, 6000% agree and it's been on my short list.

**Comment by jcsalterego** [comment]
Fixed as of https://github.com/jcsalterego/Sky.app/commit/11a474cc71a2a7f7a4c6baf8c8d8222bbf03b485
